name: IDP Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      idp-data-key: ${{ steps.submodule-hash.outputs.hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Test Leiden+
        run: pnpm test:leiden-plus

      - name: Test Leiden Translation
        run: pnpm test:leiden-trans

      - name: Get IDP Data
        run: pnpm test:idp:get-data

      - name: IDP tests – edition
        run: pnpm test:idp:edition

      - name: IDP tests – translation
        run: pnpm test:idp:translation