name: IDP Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  idp-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
        
      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use your project's Node.js version
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Cache Docker layers
      - name: Restore Docker layers
        id: cache-docker-layers-restore
        uses: actions/cache/restore@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('test/docker-compose.yml') }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Create docker-compose-cache.json
      - name: Create docker-compose-cache.json
        run: |
          echo '{
            "target": {
              "xsugar": {
                "cache-from": [
                  "type=local,src=/tmp/.buildx-cache"
                ],
                "cache-to": [
                  "type=local,dest=/tmp/.buildx-cache"
                ],
                "output": [
                  "type=docker"
                ]
              }
            }
          }' > /tmp/docker-compose-cache.json
          
      # Pre-build the Docker image
      - name: Pre-build xsugar Docker image
        run: |
          docker buildx bake --file test/docker-compose.yml --file /tmp/docker-compose-cache.json
        env:
          DOCKER_BUILDKIT: 1

      # Cache Docker layers
      - name: Save Docker layers
        id: cache-docker-layers-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ steps.cache-docker-layers-restore.outputs.cache-primary-key }}


      # IDP data
      - name: Get submodule hash
        id: submodule-hash
        run: |
          echo "hash=$(git ls-tree HEAD test/data/idp.data | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: Restore IDP data cache
        id: cache-idp-data-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            test/data/idp.data
          # invalid if idp data changed  
          key: idp-data-${{ steps.submodule-hash.outputs.hash }}

      - name: Get IDP Data
        if: steps.cache-idp-data-restore.outputs.cache-hit != 'true'
        run: pnpm test:idp:get-data

      - name: Save IDP data cache
        id: cache-idp-data-save
        uses: actions/cache/save@v4
        with:
          path: |
            test/data/idp.data
          key: ${{ steps.cache-idp-data-restore.outputs.cache-primary-key }}


      # Processed test data

      - name: Restore test data cache
        id: cache-test-data-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            test/data/roundtrips
          # invalid if idp data or xsugar version changed
          key: test-data-${{ hashFiles('test/data/idp.data/.git') }}-${{ hashFiles('test/docker-compose.yml') }}

      - name: Prepare test data
        run: pnpm test:idp:prepare:translation
        env:
          DOCKER_BUILDKIT: 1

      - name: Save test data cache
        id: cache-test-data-save
        uses: actions/cache/save@v4
        with:
          path: |
            test/data/idp.data
          key: ${{ steps.cache-test-data-restore.outputs.cache-primary-key }}
              
      - name: Xsugar cleanup
        run: pnpm test:idp:xsugar:down


      # - name: Test edition
      #  run: pnpm test:idp:edition

      - name: Test translation
        run: pnpm test:idp:translation
